# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: array-formatter 1.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "array-formatter".freeze
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Alan K. Stebbens".freeze]
  s.date = "2017-02-02"
  s.description = "    A simple gem to reformat an array of arrays into one of several string\n    formats: HTML table; CSV; ASCII table; YAML\n".freeze
  s.email = "aks@stebbens.org".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".gitignore",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "array-formatter.gemspec",
    "lib/array/formatter.rb",
    "lib/array/formatter/version.rb",
    "test/helper.rb",
    "test/ref/a-ascii.txt",
    "test/ref/a-csv.txt",
    "test/ref/a-html.txt",
    "test/ref/a-unicode.txt",
    "test/ref/a-unicode_single.txt",
    "test/ref/a-yaml.txt",
    "test/ref/a-yml.txt",
    "test/ref/b-ascii.txt",
    "test/ref/b-csv.txt",
    "test/ref/b-html.txt",
    "test/ref/b-unicode.txt",
    "test/ref/b-unicode_double.txt",
    "test/ref/b-unicode_mixed.txt",
    "test/ref/b-yaml.txt",
    "test/ref/b-yml.txt",
    "test/test-array-formatter.rb"
  ]
  s.homepage = "https://github.com/aks/array-formatter".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.7".freeze
  s.summary = "Format an array of arrays in one of serveral string formats".freeze
  s.test_files = ["test/helper.rb".freeze, "test/ref/a-ascii.txt".freeze, "test/ref/a-csv.txt".freeze, "test/ref/a-html.txt".freeze, "test/ref/a-unicode.txt".freeze, "test/ref/a-unicode_single.txt".freeze, "test/ref/a-yaml.txt".freeze, "test/ref/a-yml.txt".freeze, "test/ref/b-ascii.txt".freeze, "test/ref/b-csv.txt".freeze, "test/ref/b-html.txt".freeze, "test/ref/b-unicode.txt".freeze, "test/ref/b-unicode_double.txt".freeze, "test/ref/b-unicode_mixed.txt".freeze, "test/ref/b-yaml.txt".freeze, "test/ref/b-yml.txt".freeze, "test/test-array-formatter.rb".freeze]

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<minitest>.freeze, ["~> 5.3"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.0"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.3"])
      s.add_development_dependency(%q<rake>.freeze, ["~> 0"])
    else
      s.add_dependency(%q<minitest>.freeze, ["~> 5.3"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.0"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.3"])
      s.add_dependency(%q<rake>.freeze, ["~> 0"])
    end
  else
    s.add_dependency(%q<minitest>.freeze, ["~> 5.3"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.0"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.3"])
    s.add_dependency(%q<rake>.freeze, ["~> 0"])
  end
end

